name: Create tagged release

on:
  push:
    branches:
      - main
    paths:
      - "kikuchipy/release.py"

jobs:
  create-tagged-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ runner.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install outdated
    - name: Check branch version against PyPI version
      run: |
        eval x=($(python check_version.py))
        echo "MAKE_RELEASE=${x[1]}" >> $GITHUB_ENV
        echo "PYPI_VERSION=${x[2]}" >> $GITHUB_ENV
        echo "BRANCH_VERSION=${x[3]}" >> $GITHUB_ENV
    - name: Make tagged release
#      if: ${{ env.MAKE_RELEASE == 'true' }}
      run: |
        echo "${{ env.MAKE_RELEASE }}"
        echo "${{ env.PYPI_VERSION }}"
        echo "${{ env.BRANCH_VERSION }}"
#        echo "Make tagged release!"
